feat: signup, login and login with google functionality
NasimFatima/LetsEat pull request #1
Opened 2020-12-14 06:11 UTC by NasimFatima

2020-12-14 10:23 UTC, muhammad-tazeem-imran requested changes
`user/model/user.py` and `user/models.py` seems to contain duplicate logic.

2020-12-14 10:23 UTC, muhammad-tazeem-imran commented on letseat/settings.py
> +        'rest_framework.permissions.AllowAny',
Why do we have conflicting classes here?

2020-12-14 10:23 UTC, muhammad-tazeem-imran commented on letseat/settings.py
> +    'JWT_AUTH_HEADER_PREFIX': 'JWT',
Lets go with standard approach, use `Bearer` here.

2020-12-14 10:23 UTC, muhammad-tazeem-imran commented on letseat/settings.py
> +JWT_AUTH = {
If we are not changing the default value, we do not have to explicitly define them.

2020-12-14 10:23 UTC, muhammad-tazeem-imran commented on letseat/settings.py
>  https://docs.djangoproject.com/en/3.1/ref/settings/
Settings can relate to specific apps or third party apps. It is good practice to group together the settings for an app, and mention the app name as well.

2020-12-14 10:23 UTC, muhammad-tazeem-imran commented on user/admin.py
> +from .models import User
Where are we using this?

2020-12-14 10:23 UTC, muhammad-tazeem-imran commented on user/model/user.py
> +# Create your models here.
Lets remove unnecessary comments.

2020-12-14 10:23 UTC, muhammad-tazeem-imran commented on user/services/loginService.py
> +        """[Format Response based on Setting]
Can we please avoid adding doc-strings on functions where
a) functions are either too simple to require any explanation
b) the doc-strings do not help in understanding the method at all

No comment is better than a badly written comment*

2020-12-24 08:10 UTC, muhammad-tazeem-imran requested changes

2020-12-24 08:10 UTC, muhammad-tazeem-imran commented on user/models.py
> +    role = models.IntegerField(blank=True, null=True)
roles vs groups, how are we distinguishing between the two.

2020-12-24 08:10 UTC, muhammad-tazeem-imran commented on user/serializer/user_serializer.py
> +class CustomRegisterSerializer(serializers.Serializer):
Let's avoid copy-pasting code from the libraries. Lets refactor this accordingly.

2020-12-24 08:10 UTC, muhammad-tazeem-imran commented on user/services/loginService.py
> +        if getattr(settings, 'REST_USE_JWT', False):
Since we have enabled the REST_USE_JWT in the settings we can assume that it will always be true in the project.

2020-12-24 08:10 UTC, muhammad-tazeem-imran commented on user/urls.py
> +    url(r'dummy/', get_user_dummy_method, name='get user dummy method'),
Avoid pushing the testing code.

2020-12-24 08:10 UTC, muhammad-tazeem-imran commented on user/view/user.py
> +            user = User.objects.get(email=data['email'])
Can we use `get_or_create` here?

2020-12-24 08:10 UTC, muhammad-tazeem-imran commented on user/services/loginService.py
> +        if getattr(settings, 'REST_USE_JWT', False):
Do we need to check here?

2020-12-24 08:10 UTC, muhammad-tazeem-imran commented on user/view/user_groups.py
> +def get_all_roles(request):
Lets look up a way to do this in django.

2021-01-05 06:33 UTC, muhammad-tazeem-imran requested changes

2021-01-05 06:33 UTC, muhammad-tazeem-imran commented on menu/models.py
> +from .model.menu_item import MenuItems
Why not create all the models directly here in the `models.py` file?

2021-01-05 06:33 UTC, muhammad-tazeem-imran commented on menu/urls.py
> +]
Can we find  a simpler way to do this?

2021-01-05 06:33 UTC, muhammad-tazeem-imran commented on menu/view/menu.py
> +from rest_framework import status, viewsets
Why do we have this view/ subdirectory?

2021-01-05 06:33 UTC, muhammad-tazeem-imran commented on user/view/user.py
>              print(err)
Lets remove print statements.

2021-01-05 06:33 UTC, muhammad-tazeem-imran commented on user/services/loginService.py
>  class LoginService(GenericAPIView):
Lets write this as functional helpers instead of a class.

2021-01-12 13:55 UTC, muhammad-tazeem-imran requested changes
Try to run your code through a linter to catch the common linting errors like unused imports.

2021-01-12 13:55 UTC, muhammad-tazeem-imran commented on menu/views.py
> +        try:
Do we need to catch the exception if we are throwing 500 in the end? What is the default behavior of django in case of an error?

2021-01-12 13:55 UTC, muhammad-tazeem-imran commented on user/views.py
> +class LoginView(GenericAPIView):
Can we merge both the logins into one class?

2021-01-12 13:55 UTC, muhammad-tazeem-imran commented on menu/models.py
> +        db_table = "menu_items"
Do we need to explicitly define db_table, each time?

2021-01-12 13:55 UTC, muhammad-tazeem-imran commented on menu/serializers/menu_serializer.py
>  class MenuItemSerializer(serializers.ModelSerializer):
Can we unify the serializers in one main file as we did the models and views?

2021-01-12 13:55 UTC, muhammad-tazeem-imran commented on user/views.py
> +        if jwt_settings.JWT_AUTH_COOKIE:
Are we enabling the JWT_AUTH_COOKIE in settings?

2021-01-13 06:18 UTC, NasimFatima commented on user/views.py
> +class LoginView(GenericAPIView):
Both methods are different So its not appropriate to merge them in one class.

2021-01-14 07:53 UTC, muhammad-tazeem-imran commented on user/views.py
> +class LoginView(GenericAPIView):
We are using the same helper methods in both, so they do have similarities. Also since they accomplish the same thing so to that end they should be placed in the same class.

2021-01-22 14:30 UTC, muhammad-tazeem-imran requested changes

2021-01-22 14:30 UTC, muhammad-tazeem-imran commented on orders/models.py
> +    order_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True,
Lets remove this from common.

2021-01-22 14:30 UTC, muhammad-tazeem-imran commented on orders/models.py
> +    status = models.CharField(max_length=20, default='Pending')
Let convert status to string choices.

2021-01-22 14:30 UTC, muhammad-tazeem-imran commented on orders/urls.py
> +]
Do we need to do this?

2021-01-22 14:30 UTC, muhammad-tazeem-imran commented on orders/views.py
> +@permission_classes([IsAuthenticated])
Lets define it as an attribute, for a more consistent code.

2021-01-22 14:30 UTC, muhammad-tazeem-imran commented on orders/views.py
> +                orders = Orders.objects.all().exclude(is_checkedout=False).order_by('-id')
```
if not request.user.groups.filter(name='Customer').exists():
    orders = self.get_queryset().exclude(is_checkedout=False).order_by('-id')
else:
    ...
```

2021-01-22 14:30 UTC, muhammad-tazeem-imran commented on orders/views.py
> +    def list(self, request, **kwargs):
Lets create a separate endpoint for active items.

2021-01-22 14:30 UTC, muhammad-tazeem-imran commented on user/views.py
> +@permission_classes([AllowAny])
Lets revert this to the original value.

2021-01-22 14:30 UTC, muhammad-tazeem-imran commented on user/views.py
> +                response = self.google_login(access_token)
```
return self.google_login(access_token)
```

2021-01-22 14:30 UTC, muhammad-tazeem-imran commented on user/services/loginService.py
>  def login(self):
Lets move this to the LoginView.

2021-01-22 14:30 UTC, muhammad-tazeem-imran commented on user/views.py
>          r = requests.get(
r -> google_response or google_api_response.

2021-01-22 14:30 UTC, muhammad-tazeem-imran commented on user/views.py
>              return response
`return login(self)` ?

2021-01-27 06:47 UTC, muhammad-tazeem-imran requested changes

2021-01-27 06:47 UTC, muhammad-tazeem-imran commented on user/views.py
> +    permission_classes = [IsAuthenticated, ]
A trailing comma is needed only if you use parenthesis not with square brackets.
`permission_classes = [IsAuthenticated, ]`

2021-01-27 06:47 UTC, muhammad-tazeem-imran commented on user/views.py
> +            return Response({'data': {}, 'Success': False, 'Error': user.errors}, status.HTTP_200_OK)
Lets use an error code here to indicate error.

2021-01-27 06:47 UTC, muhammad-tazeem-imran commented on menu/views.py
> +        if item_categories:
Lets add a new line before the if block.

2021-01-27 06:47 UTC, muhammad-tazeem-imran commented on orders/views.py
> +
Avoid starting a code block with an empty newline.

2021-02-03 05:17 UTC, merged